# Generated by Django 4.2.2 on 2024-02-23 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultationreport',
            options={'ordering': ('-created_at',), 'verbose_name': 'Consultation Report', 'verbose_name_plural': 'Consultation Reports'},
        ),
    ]
